# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: golang-github-facebookincubator-go2chef.spec
files_to_sync:
  - golang-github-facebookincubator-go2chef.spec
  - .packit.yaml

upstream_package_name: go2chef
downstream_package_name: golang-github-facebookincubator-go2chef
actions:
  # Fetch the specfile from Rawhide, remove the snapshot and drop any patches
  post-upstream-clone: "bash -c \"curl -s https://src.fedoraproject.org/rpms/golang-github-facebookincubator-go2chef/raw/main/f/golang-github-facebookincubator-go2chef.spec | sed -e '/^Patch[0-9]/d' > golang-github-facebookincubator-go2chef.spec\""

srpm_build_deps:
  - bash
  - curl
  - sed

jobs:
- job: copr_build
  trigger: commit
  owner: "@meta"
  project: go2chef
  targets:
    - fedora-all-aarch64
    - fedora-all-i386
    - fedora-all-ppc64le
    - fedora-all-s390x
    - fedora-all-x86_64
- job: copr_build
  trigger: pull_request
  owner: "@meta"
  project: go2chef
  targets:
    - fedora-all-aarch64
    - fedora-all-i386
    - fedora-all-ppc64le
    - fedora-all-s390x
    - fedora-all-x86_64
